name: Continuous Integration

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v2
      with: { python-version: "3.8" }

    - name: Install dependencies
      run: pip3 install conan
        && conan profile new default --detect
        && conan profile update settings.compiler.libcxx=libstdc++11 default
        && conan install . -if conan

    - name: Configure
      run: cmake --preset=ci-ubuntu

    - name: Build
      run: cmake --build build -j 2

    - name: Test
      working-directory: build
      run: ctest --output-on-failure -j 2
